[package]
name = "retry-if"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
retry-if-macro = { version = "0.1.0", path = "retry-if-macro", default-features = false }
tokio = { version = "1.36.0", features = ["full", "test-util"] }

[dev-dependencies]
trybuild = "1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
retry-if = { path = ".", features = ["tracing"] }

[features]
tracing = ["retry-if-macro/tracing"]
