[package]
name = "retrys-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
tracing = { version = "0.1.4", optional = true }

[features]
tracing = ["dep:tracing"]

[lib]
proc-macro = true
